name: conformal 
channels:
    - anaconda
    - conda-forge
    - pytorch
dependencies:
    - python=3.9
    - pip
    - numpy
    - numpy-base
    - matplotlib
    - matplotlib-base
    - scipy
    - scikit-image
    - pytorch
    - torchvision
    - torchaudio
    - pandas
    - pillow=6.1
    - imageio
    - seaborn
    - tqdm
    - pyyaml
    - pycocotools
    - cudatoolkit=11.6
    - faiss-gpu
    - ipykernel
    - catboost
    - jupyter
    - pip:
        - randaugment
        - gdown
        - detoxify
